### ISSUE TITLE
high cpu load

### ISSUE THREAD

**Issue by allkhor** [JacquesLucke/animation-nodes#108]
Hi, after this commit c56d3542d294bbbd3b7f24f9d5b68d7a660bf061, I found increase CPU load. 
Before it, when I add node "object --> transform output", cpu load little increase and if I unchecked all in performance(settings) tab, cpu load normalized. After this commit, cpu high load every time, without nodes, and unchecked all in performance(settings) tab not work.

**Comment by JacquesLucke** [comment]
oh thanks for that detailed issue! I will check it soon :)

**Comment by JacquesLucke** [comment]
can you maybe comment out that line in your local copy and try again?: https://github.com/JacquesLucke/animation-nodes/blob/master/mn_execution.py#L29

**Comment by balaamsdonkey** [comment]
Hi. I reported the same issue on the blenderartists forum. I commented out the redraw_areas_if_possible() call as you recommended, and this seems to have solved the cpu usage issue that I was experiencing.

**Comment by allkhor** [comment]
Thank's, it work! What about this function, without redraw we have some issues(draw glitches)?

**Comment by JacquesLucke** [comment]
Normally blender redraws only parts of the whole ui when you change something, this function just tells Blender to redraw everything so that you have better realtime feedback.
Maybe I can make this optional :)
