### ISSUE TITLE
Get Object Properties?

### ISSUE THREAD

**Issue by kopias** [JacquesLucke/animation-nodes#110]
would be nice to have a central place for global settings (variables) per object
currently i cant use same value (or maybe i can?) outside and inside loops
plus using object properties is a nice temp ui in 3dviewport

will try to use script node to get object properties... 
but thats for later since im just getting started

**Comment by JacquesLucke** [comment]
Can you maybe make a rough mockup of what you exactly want?
Normally you should be able to use the same values in and outside loops

the temp ui is something I worked on a few months ago but I never finished this. Maybe I can restart this later, but I'm not sure if this will happen

**Comment by kopias** [comment]
First: I was dumb enough to assume that "Object Attribute Input" works like in cycles shader. Instead it does exactly what i wanted. Second issue is also due to my lack of knowledge.
Sorry for that - i will try to avoid this in the future.

The simple temp ui example i was trying to accomplish: http://www.pasteall.org/blend/35239
... using "Object Attribute Input" like in this simple example makes my laptop hot :)
... also deleting those attribute nodes and hitting undo breaks nodes update.
Tested on 2.74rc3 win7x64

**Comment by kopias** [comment]
it seams this is just the way animation nodes work, they update constantly even without ui events or frame change. maybe undo breaking should be in separate issue?

btw. using those nodes is so much fun... thx

**Comment by JacquesLucke** [comment]
No problem. Having issues is just a step in the learning process :)

Yeah undo is a problem with this addon. I have to admit that I don't think that I can solve this issue :/

Thanks :)

**Comment by og76** [comment]
On a general note, yes object attribute is your friend, and mine the best.
Though for cuteness, a node like Object settings (properties?or what ..) may do if it just works like the cycles material one
select the object
-list of shapekeys/constraints/modifiers >select one
-list of respective props

but be ware, this is more of a pandora's box, why not also layers, why not visibility, why not everything etc etc .. Well, we already have everything, obj attr ...

ps. hot is indeed quite an issue here too. not sure if obj attr is more special ...

**Comment by kopias** [comment]
@og76 I uncheck all updates in performance panel and use those refresh buttons on 'loop call' nodes when its getting too hot (or when on battery)
