### ISSUE TITLE
Sound Bake operator sets to av-sync

### ISSUE THREAD

**Issue by kopias** [JacquesLucke/animation-nodes#111]
Bake operator always sets sync mode to av-sync.
Its just that for me frame dropping sync mode is much better choise
and after every sound bake i need to change that setting (or change default in addon code).
Maybe this could be in addon preference?

**Comment by JacquesLucke** [comment]
look in the right side bar while the sound bake node is selected and uncheck the "Set Audio Sync Mode" checkbox. (after you redownloaded the addon of course)

**Comment by larrythegroove** [comment]
As requested coming through forum rather than Email - a few questions :+1: 

1. can't find 'Arrange' nodes
2. are there any examples of the Mesh nodes in use ?

**Comment by JacquesLucke** [comment]
The forum I mean is here: http://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes :p

1. 
![arrange node](https://cloud.githubusercontent.com/assets/5881326/7009785/ff9b63e2-dc9c-11e4-8a83-13ec63faa338.PNG)
2. Therefor please look through the forum thread. There are quite a few examples. If you have a specific question please ask it there :)
