### ISSUE TITLE
Append to list text list not working in a loop

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation-nodes#116]
I bumped into this bug, inside a loop, append to list to a text just gives the last element. For comparison same works well for float list

text fun append to list bug.blend
https://drive.google.com/file/d/0BzzAoBwXO8dsNk16MGRiQ0lVU0U/view?usp=sharing

**Comment by og76** [comment]
not fixed!!! now the float list does not work also, where float list/append was ok
blend
https://drive.google.com/file/d/0BzzAoBwXO8dscGQ3bl9saVNwVWs/view?usp=sharing

**Comment by JacquesLucke** [comment]
hmm everything works as I would expect in your new .blend.

In fact the bug you found wasn't the real bug. The bug was in the float list node, not the text list node.
Basically the loop is executed 5 times in your example. And each time a new text/number list is created and one element is added. Looks fine from my perspective.

**Comment by og76** [comment]
here's a capture 
1 old version, float gives me a list [7,2,3,] - correct - text gives only one element
![append bug old](https://cloud.githubusercontent.com/assets/11709974/6982185/89138c14-da16-11e4-837f-6ee2ac363bb7.JPG)

2 new after fix, float gives also just one element
![append bug new](https://cloud.githubusercontent.com/assets/11709974/6982148/fe6bf466-da15-11e4-9547-ca7883ae0f65.JPG)

**Comment by JacquesLucke** [comment]
what you think is correct is actually not correct.. :/ 
a list with one element is the correct result.

**Comment by kopias** [comment]
agree with @JacquesLucke 

@og76 i think this is what you are trying to do:
![screen](https://cloud.githubusercontent.com/assets/3462746/6982345/db4b9a7c-da10-11e4-860b-db668aa2bffe.png)

**Comment by og76** [comment]
thank you kopias, now I get it , 

and now I understand the variables issue filed
normally those are variables and they should be proposed in the beginning?

But how is this consistent /expected, cause I can use other inputs along, for ex object cone and text in the pic below. 
![variables](https://cloud.githubusercontent.com/assets/11709974/6982766/ba1e611e-da1e-11e4-81d5-b4e991bac4c0.JPG)

That is what I say in the order of operations issue when it comes to loops example, cause I bumped before on such inside/outside loop issues. As non scripter it is not obvious ..

**Comment by kopias** [comment]
@og76
im not expert in this but its like global and local variables and You can use globals inside loops.

In Your example 'Cone' position is set up three times, You just dont see the jumps.
