### ISSUE TITLE
no "object replicator" node under the shiftA "object" node menu.

### ISSUE THREAD

**Issue by angusgiorgi** [JacquesLucke/animation-nodes#117]
Hi Jaques, there is no object replicator node under the shiftA "object" node menu.  There is an object list node and an object instancer node.  I downloaded what seems to be the latest zip from your github, nodes say you updated them 9 days ago.  Has this node disappeared or been superceded by another node?

**Comment by JacquesLucke** [comment]
I already answered you one youtube and changed the description of the video :)
It is called "Object Instancer" now
