### ISSUE TITLE
Suggestion: Recalculate Normals node improvement

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation-nodes#122]
In some cases, this node just get an inverted result (like Blender usually does), and we have to use another Recalculate Normal node to invert that. Maybe it's better to add a toggle on the existing node to  make an easy invert?

Example:  http://www.pasteall.org/blend/35880

**Comment by JacquesLucke** [comment]
![invert normals](https://cloud.githubusercontent.com/assets/5881326/7446118/dc22817a-f1cd-11e4-954d-332a44b4c303.PNG)

**Comment by LeonCheung** [comment]
Oh that's cool! :+1:
