### ISSUE TITLE
New Node Needed: Conditional Node

### ISSUE THREAD

**Issue by ehigiepaul** [JacquesLucke/animation-nodes#70]
This will be a simple if conditional statement that will do an operation if an action is not reached.

**Comment by LeonCheung** [comment]
@ehigiepaul I think it is now possible by using Expression node.

**Comment by azerupi** [comment]
Not really I think, but I bet you could make it work by tweaking the code a little.

If you add a little bit of code in every node that bypasses the node if the input is None and sets every output to None. This would send the info down the chain.. But it would require to change the code in every node or in the parent class.

@JacquesLucke  what do you think, could that work?

**Comment by JacquesLucke** [comment]
Changing every node and socket type is a no-go. This would add a lot of overhead and makes the system much more unstable. Instead I'm thinking about another way to do this. Wait

**Comment by azerupi** [comment]
Yeah changing all nodes is a terrible idea, but can't you do that in the parent class (mn_node_base.py > AnimationNode) ?

If you have a better alternative, that's even better ^^

**Comment by JacquesLucke** [comment]
![boolean nodes](https://cloud.githubusercontent.com/assets/5881326/6577825/d61830a2-c740-11e4-9024-9e9cd9bbc31f.jpg)

**Comment by vvFiCKvv** [comment]
nice job, it will be awsome to animate(insert keyframes) the condition socket.
is it easy to convert it to switch case for more than one condition/input? like if, elseif, else?

**Comment by azerupi** [comment]
@vvFiCKvv In my opinion that is not such a great idea, it adds a lot of "pressure" to the layout. You can chain the nodes (that's what nodes are meant for)  :)

**Comment by JacquesLucke** [comment]
![animation condition](https://cloud.githubusercontent.com/assets/5881326/6578290/98082da0-c743-11e4-9e0a-db176aaef1be.PNG)

a switch statement can be implemented later :) or you do it with multiple condition nodes

**Comment by azerupi** [comment]
Actually you could already do this by using the expression node. What would really be helpful is to bypass all the nodes in the branch if the condition is not met. Currently whit this setup a vector would get a default value of (0,0,0) instead of being bypassed altogether.

![screen](https://cloud.githubusercontent.com/assets/7647338/6583210/d2e78744-c762-11e4-8bd3-32cb617dc05b.png)

One way to do this is to add some code that runs before the execute function that would check if the input is None and in if it is bypass the execute function and return None to all output sockets. In that way you can transmit the info down the node  chain. 

Would that be possible, for example in the parent class **AnimationNode**?

**Comment by JacquesLucke** [comment]
I know what you mean and that my solution still executes all nodes. Unfortunally what you wont doesn't fit into the system...
Maybe you could use the condition node to use 'None' as object when the condition input is False. This way the other nodes won't effect anything in the scene.

**Comment by azerupi** [comment]
> Maybe you could use the condition node to use 'None' as object when the condition input is False. This way the other nodes won't effect anything in the scene.

Well that is actually already the case ;) When you don't specify a value None is used. But as you can see, the convert node outputs 0 when he receives None.. Making it less useful :)

**Comment by JacquesLucke** [comment]
can you show me an image where the convert node outputs 0? Normally it should output None

**Comment by JacquesLucke** [comment]
Ahh I see. What the convert node outputs depends on what it is connected to. Because in your example it should output a float value it will never return None, because only some types can be None like Object, Generic, ...
