### ISSUE TITLE
Clean-up Loops

### ISSUE THREAD

**Issue by azerupi** [JacquesLucke/animation-nodes#90]
I think loops should receive a little clean-up.

For now, there are 3 loop nodes in the add menu. But actually, only one of them is really required: **The loop caller**. Since the other nodes you need for a loop (**object loop** and **generic loop**) can be created directly from the **loop caller** node by pressing **New Loop**.

I think it would make more sense to rename *"loop caller"* to just *"loop"* in the add menu and remove **object loop** and **generic loop** from the add menu. 

I think this could decrease confusion for new users and make the add menu a little less crowded :wink: 

----------

PS: Since I heard you were not going to actively develop this add-on anymore. I am willing to look into this if you want.

**Comment by JacquesLucke** [comment]
Ahh yes you're right. This is there from an earlier stage of the addon

Would be cool if you can do this :)

**Comment by azerupi** [comment]
It's done, was easier than I thought.
But I am trying to solve one more quirk with the loops. When you change the loop body with the drop down menu. The sockets don't update, you have to manually press that update button next to it. It should do it automatically when that's fixed I will create a pull request :)

**Comment by JacquesLucke** [comment]
I know what you mean. This is intended. Yes, it is a bit weard but sometimes there are problems if it changes the sockets automatically. this is because the drop down menu is a dynamic enum and when I it happens multiple times to me that when I rename a loop or add a second one, the selected item changes to a random entry......

**Comment by azerupi** [comment]
ow ok, I will see then. If I can't figure out something I will leave it like it is :)

**Comment by azerupi** [comment]
After a lot of trial and error I finally got it to work when you change the loop via the dropdown menu. The sockets update accordingly to the selected loop. It doesn't seem like it causes other problems. 

It still does not update when you click on **new loop** though

**Comment by JacquesLucke** [comment]
cool, can you show me the changes? :)

**Comment by azerupi** [comment]
It does update the first time when you create a new loop and then not anymore. I also found a strange behaviour:

1. When you create a new loop for the first time, the active loop changes to that new loop. 
2. After that when you create a new loop **WHILE** you have not selected an active loop manually with the dropdown menu, the active loop will change to that new loop.
3. If you do change the active loop and then create a new loop, the active loop will **not** change.

The behaviour should always be the same: set the new loop as active loop

Do you agree?

**Comment by azerupi** [comment]
Yup I will upload what I already have :)

**Comment by azerupi** [comment]
Here https://github.com/azerupi/animation-nodes you can test it by downloading it here :)

**Comment by azerupi** [comment]
Actually it is another bug that is causing problems.
When you add a new loop, the activeLoop and selectedLoop in the dropdown menu do not match anymore... 
![screen](https://cloud.githubusercontent.com/assets/7647338/6413770/e11abe7c-be92-11e4-8813-8e937a47b31b.png)

**Comment by azerupi** [comment]
#94
