### ISSUE TITLE
Issue with vector math

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation-nodes#92]
When using Keyframe input node with Vector math, some types cannot be well generated, such as substract and crossproduct. However, with Object Info node, it would be fine. Thanks for checking.

![keyframe](https://cloud.githubusercontent.com/assets/494788/6437713/094e3934-c0fd-11e4-84a8-1db330f873bc.png)

UPDATE:

Something interesting is that it can be temporarily “solved” by using two more nodes to work in-between. (Strange huh? )

![keyframe2](https://cloud.githubusercontent.com/assets/494788/6437814/0b048ebc-c0fe-11e4-9069-ac00dce7ed65.png)

**Comment by JacquesLucke** [comment]
I think I know the problem. Its because at some point I decided to always use a mathutils.Vector object for vectors instead of only a list. It seams I forgot to change it there.

Unfortunally I currently don't have a network connection for my pc. I will fix it as soon as my wlan works again

**Comment by LeonCheung** [comment]
Oh, cool, so it is really a problem.... It cost me almost a whole day to figure out why I cannot parent the lamp to the  object. :sob:  like this:

![key](https://cloud.githubusercontent.com/assets/494788/6438152/9394f3d6-c101-11e4-8f18-bf2e71987a49.png)

**Comment by JacquesLucke** [comment]
I just uploaded the fix for the vector problem. can you test it please? :)

Hmm not sure what you exactly want. To parent objects I would do this:
![parent objects](https://cloud.githubusercontent.com/assets/5881326/6513356/ac85d592-c37a-11e4-9079-9763673b9e0c.PNG)

**Comment by LeonCheung** [comment]
Sure I think we are the same.  :)  The reason why I setup like that is I want to keep the Child position unchanged relative to the parrent. I I think it is better to use Vector Math to generate its LOCAL position after parenting, isn't it?  Anyway, thank you for fixting that, and... Glad you are back!

**Comment by LeonCheung** [comment]
Hmm, I didn't see the master changes, are you sure it has been successfully uploaded?

**Comment by JacquesLucke** [comment]
https://github.com/JacquesLucke/animation-nodes/commit/0d81ebbf615b421c2baca8107f2d116f64e160ad

**Comment by JacquesLucke** [comment]
I have to look at it later again :) (at your parenting issue)

**Comment by LeonCheung** [comment]
I just didn't see it in the master yet. Got it, anyway. :P Btw, I'm currently doing something cool ( or crazy), which might need new features aids from you LOL, will post request in a minute.  :smile:

**Comment by LeonCheung** [comment]
I think it still happens with the latest version.  :(

**Comment by LeonCheung** [comment]
Yeah! Perfect now. :tada:
