### ISSUE TITLE
Why grouping failed?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation-nodes#93]
Hi, in the attached case, I'm trying to group the nodes in the white box, but when I tried to refresh the group caller, it failed with error message.

http://www.pasteall.org/blend/34827

I don't know if this is a bug or something. Thanks for checking!

**Comment by JacquesLucke** [comment]
I will check it when I have my internet connection back. I'm quite limited in what I can do currently....

**Comment by JacquesLucke** [comment]
hmm. Quite difficult to find the exact reason for your error message. Can you maybe try to simplify the example? .. :/

**Comment by LeonCheung** [comment]
To see what I mean, please see thsi video. http://youtu.be/mNr8JJZILUc And you can see I added some  "redundancy" nodes, that's because, if not, the caller will failed to generate. However, I cannot reproduce it everytime...

I know this setup sucks, but hope I exposed something fishy.  :)

**Comment by JacquesLucke** [comment]
Sorry, I see that something doesn't work there but I cannot exactly see what it is in such a complex setup..

**Comment by LeonCheung** [comment]
Hey, I think I know why, I nearly forgot that you mentioned before that we cannot use the same node inside and outside the loop, so the same rule also applies to Group Caller, I bet?

**Comment by JacquesLucke** [comment]
thats true. Groups, Loops and other networks are not allowed to have links between them . (wouldn't make sense otherwise)

**Comment by LeonCheung** [comment]
Yeah, then this issue can be closed for sure. :D Sorry for troubling with a uggly setup. (this is one method I was trying to make a subtitle editor before your regex improvement on expression)

**Comment by JacquesLucke** [comment]
haha good! :D

**Comment by LeonCheung** [comment]
liero's latest post make me thinking that there would be an exception, which is, when using a loop call inside a loop call. I know, it just passes values there, but this could be a little tip and clarification for any upcoming manual. After all, Loop node itself is also a node, (technically speaking?).

Something like this:
![666](https://cloud.githubusercontent.com/assets/494788/6613505/1ece3fba-c8c9-11e4-99fd-00511486836d.jpg)

**Comment by JacquesLucke** [comment]
yes I loop call is also just a node. It's like a special group :p but it executes the subnetwork multiple times :D
I'm not sure if I understand correctly what you mean..

**Comment by LeonCheung** [comment]
Sure it is.  :)
