### ISSUE TITLE
Suggestion: Restore Keyframe

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation-nodes#97]
When building the trees, especially for users not so experienced, they can easily get the initial keyframes messed up, and no easier way to go back to the initial state, even they cut off the noodles,  including Ctrl Z for many times, though we can copy the value then paste them back to object's N panel or somewhere else (Shame on myself, I sometimes encounter this awkward thing...).

So I may propose a button to restore object(s) to the initial position(s), etc, which are manually set by user (I mean currently by manually pressing "Set from Current" button).

I think it is better for this button to show itself in the same panel where we set keyframes?

**Comment by JacquesLucke** [comment]
So you mean that before the user starts creating a node tree he presses a button and all transformations are saved?
later he can press a different button to restore this?

**Comment by LeonCheung** [comment]
I mean this is mainly useful to "reset" the current transformation info to the initial transform data (supposing it is not being driven by Animation Nodes yet). You know, sometime people just "lost" their objects after linking something in the tree, even though they cut off the link, the object is still missing. Normally, when they go to the N panel to check for the location, they suddenly found that it is located at miles away... Sadly, sometimes this is caused by iteration and Ctrl Z can do nothing about this.

**Comment by LeonCheung** [comment]
To make my idea even shorter: is it considerable to provide a button to reset object's properties with the inivitial kayframe values anytime?

**Comment by JacquesLucke** [comment]
In fact I don't know where to take the location, rotation, etc. from when you want to reset it. 
I cannot store the whole .blend file to go back to it later... But the user can do that..

**Comment by LeonCheung** [comment]
Haha, I feel we are misunderstanding each other. Let me try this way:
![illu](https://cloud.githubusercontent.com/assets/494788/6604690/216634c6-c865-11e4-8ece-74c0c00a31cb.jpg)

Can we easily replace A B C values with A' B' C'  at anytime when possible?

**Comment by JacquesLucke** [comment]
Ahhh. I think I know what you mean :D

**Comment by JacquesLucke** [comment]
the operator should reset all the selected objects which have a Initial Transform, right?

**Comment by LeonCheung** [comment]
Exactly, LOL, I'm speechless here.

**Comment by JacquesLucke** [comment]
why?

**Comment by LeonCheung** [comment]
Because you describe it very well with only a few words.

**Comment by LeonCheung** [comment]
And, do you think this woudl be a useful feature to have?

**Comment by JacquesLucke** [comment]
hahaha ok
yes I think that shouldn't be hard
stop the time. I start now haha

**Comment by JacquesLucke** [comment]
rough implementation is in master

**Comment by LeonCheung** [comment]
Cool! less than 6 mins. You break the record, again.  XP

**Comment by JacquesLucke** [comment]
haha so now I have to continue making homework for school..
good that you came with that request :D and we see again that good communication is essential if you want a specific feature

**Comment by LeonCheung** [comment]
Totally agree. See you around.  :)

**Comment by JacquesLucke** [comment]
https://github.com/JacquesLucke/animation-nodes/commit/ea7a4189ea562c909bea42b3d220792f3f363126
