### ISSUE TITLE
Object List node hangs with huge lists

### ISSUE THREAD

**Issue by 3delic** [JacquesLucke/animation-nodes#98]
Enable hiding the list itself, without hiding the action buttons to append objects.

**Comment by LeonCheung** [comment]
For very large amount of objects, I recommend to use Object Group Input node. I tested with over 10,000 objects, it works OK.

**Comment by 3delic** [comment]
Yes,  Object Group, Tested with 3500 objects, works fine, thx.

**Comment by LeonCheung** [comment]
But yeah, I did think about the same suggestion BEFORE the object group input node was implemented. So, vote +1 for this idea.
