### ISSUE TITLE
Invert list node Request

### ISSUE THREAD

**Issue by 3delic** [JacquesLucke/animation-nodes#99]
a node to invert a list, maybe also options to clamp, delay or shuffle a list.

**Comment by JacquesLucke** [comment]
you can already shuffle lists,
what do you mean with 'delay'?

**Comment by 3delic** [comment]
I guess delay, decay and shuffle means the same for a list index. changing the relative position.

**Comment by 3delic** [comment]
It works fine, I use it already, thx a lot.

**Comment by JacquesLucke** [comment]
Okay, great :)
